#!/bin/bash

if [[ $1 ]] ; then
	echo " *** BUILDING FOR X86-64 (SSE3) ***"
	sleep 2
fi

LUX_TAG="$2"
ROOT="/root/luxbuild"
TARGET="/root/luxbuild/target-64-sse3"
WORK="/tmp/luxbuild"
DIST="${ROOT}/distfiles"
DATE=`date "+%y%m%d"`
TAG="gcc452-x86_64-sse3-${DATE}-${LUX_TAG}"

# core2 building flags
GENERIC_FLAGS="-mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -O2 -pipe -mfpmath=sse -fPIC"
LUX_FLAGS="-mtune=generic -static-libgcc -mmmx -msse -msse2 -msse3 -mssse3 -O3 -pipe -mfpmath=sse -ftree-vectorize -fno-math-errno -fno-signed-zeros -fno-trapping-math -fassociative-math -fno-rounding-math -fno-signaling-nans -fcx-limited-range -DBOOST_DISABLE_ASSERTS -floop-interchange -floop-strip-mine -floop-block -fsee -ftree-loop-linear -ftree-loop-distribution -ftree-loop-im -fivopts -ftracer -DHAVE_PTHREAD_H -L${DIST}/stdc64 -L${DIST}/python64 -fPIC"

# x86_64
CHOST="x86_64-pc-linux-gnu"
MAKEOPTS="-j5"

if ! $ROOT/build $1 "$ROOT" "$TARGET" "$WORK" "$DIST" "$LUX_TAG" "$GENERIC_FLAGS" "$LUX_FLAGS" "$CHOST" "$MAKEOPTS" ; then
    exit 1
fi

if ! $ROOT/install "$TARGET" "$LUX_TAG" "$TAG" ; then
    echo " * Installation FAILED"
else
    echo " * Installed successfully to $TARGET/$LUX_TAG"
    echo " * DONE"
fi

