# A minimal setup to get a guest machine with docker running.
#
# We're using the default vagrant file sharing which means that all
# files in this directory and below are available under /vagrant on
# the guest.
#
# To build luxrender using this virtual machine:
#
# $ vagrant up
# $ vagrant ssh
# $ hg clone https://bitbucket.org/luxrender/linux linux
# $ cd linux
# $ hg update docker_integration
# $ docker build -t luxrender/linux-build docker-luxrender
# $ docker run -it luxrender/linux-build
#

$script = <<SCRIPT
set -e

cat >/etc/resolv.conf <<EOL
nameserver 8.8.8.8
nameserver 8.8.4.4
EOL

# We are running the docker installation script in a subshell since
# it exits on completion
(curl -sSL https://get.docker.com/ | sh)

sudo gpasswd -a vagrant docker
sudo apt-get update && sudo apt-get install mercurial

WORKDIR=/vagrant


"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "14.04"
  config.vm.box_check_update = false
#  config.vm.provision "docker"
  config.vm.provision "shell", inline: $script
  config.vm.network "private_network", ip: "192.168.50.3"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off" ]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off" ]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]    
    v.memory = 4096
    v.cpus = 2
  end
end
