#!/bin/bash

if [[ ! $2 ]] ; then
	echo " * Unable to install"
	exit 1
fi

TARGET=$1
LUX_TAG=$2

sleep 5
echo
echo " * Installing tag $TARGET/$LUX_TAG"

rm -rf $TARGET/$LUX_TAG
mkdir $TARGET/$LUX_TAG

mkdir $TARGET/$LUX_TAG/bin
cp $LUX_TAG/bin/luxcoreui $LUX_TAG/bin/luxcoreconsole $TARGET/$LUX_TAG/bin

mkdir $TARGET/$LUX_TAG/lib
cd $TARGET/lib
cp --preserve=links lib*.so* $TARGET/$LUX_TAG/lib
cd ../..

cp $LUX_TAG/README.md $TARGET/$LUX_TAG
cp $LUX_TAG/COPYING.txt $TARGET/$LUX_TAG
cp $LUX_TAG/AUTHORS.txt $TARGET/$LUX_TAG
mkdir -p $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/cornell.cfg $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/cornell.scn $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/Khaki.ply $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/HalveRed.ply $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/DarkGreen.ply $TARGET/$LUX_TAG/scenes/cornell
cp $LUX_TAG/scenes/cornell/Grey.ply $TARGET/$LUX_TAG/scenes/cornell

cd $TARGET
tar -cvjf ${LUX_TAG}.tar.bz2 $LUX_TAG
cd ..

echo
